INTERACTIVE_MODELS_PATH: "./experiments/iter_mask/cocolvis_hrnet18s/000_first-try/checkpoints/"
EXPS_PATH: "./experiments"


# Evaluation datasets
GRABCUT_PATH: "/home/admin/workspace/project/data/datasets/GrabCut"
BERKELEY_PATH: "/home/admin/workspace/project/data/datasets/Berkeley"
DAVIS_PATH:  "/home/admin/workspace/project/data/datasets/DAVIS"
COCO_MVAL_PATH: "/home/admin/workspace/project/data/datasets/COCO_MVal"
PASCALVOC_PATH: "/home/admin/workspace/project/data/datasets/VOC2012/VOCdevkit/VOC2012"
DAVIS585_PATH: "/home/admin/workspace/project/data/datasets/InterDavis/Selected_480P"
BraTS_PATH: "/playpen-raid2/qinliu/data/BraTS20"
ssTEM_PATH: "/playpen-raid2/qinliu/data/ssTEM"
OAIZIB_PATH: "/playpen-raid2/qinliu/data/OAI-ZIB"
OAI_PATH: "/playpen-raid2/qinliu/data/OAI"
HARD_PATH: "/playpen-raid2/qinliu/data/HARD"



# Train datasets
SBD_PATH:  "/home/admin/workspace/project/data/datasets/SBD/dataset"
COCO_PATH: "/home/xizhi.cx/data/dataset/COCO"
LVIS_v1_PATH: "/home/admin/workspace/project/data/datasets/COCO_LVIS"
OPENIMAGES_PATH: "/home/xizhi.cx/data/dataset/OpenImage"
PASCALVOC_PATH: "/playpen-raid2/qinliu/data/PascalVOC"
ADE20K_PATH: "/home/admin/workspace/project/data/datasets/ADE20K"
LVIS_PATH: "/home/admin/workspace/project/data/datasets/COCO_LVIS"

# Extra options for training
THINOBJECT_PATH: "/home/admin/workspace/project/data/datasets/ThinObject/ThinObject5K"
MSRA10K_PATH: "/home/admin/workspace/project/data/datasets/Saliency/MSRA10K_Imgs_GT/Imgs"
DUT_TR_PATH: "/home/admin/workspace/project/data/datasets/Saliency/DUTS-TR/DUTS-TR-Image"
DUT_TE_PATH: "/home/admin/workspace/project/data/datasets/Saliency/DUTS-TE/DUTS-TE-Image"
YTBVOS_PATH: "/home/admin/workspace/project/data/datasets/YTBVOS"
HFLICKER_PATH: "/home/admin/workspace/project/data/datasets/HFlickr"

# Extra options for training
THINOBJECT_PATH: "/home/admin/workspace/project/data/datasets/ThinObject/ThinObject5K"
MSRA10K_PATH: "/home/admin/workspace/project/data/datasets/Saliency/MSRA10K_Imgs_GT/Imgs"
DUT_TR_PATH: "/home/admin/workspace/project/data/datasets/Saliency/DUTS-TR/DUTS-TR-Image"
DUT_TE_PATH: "/home/admin/workspace/project/data/datasets/Saliency/DUTS-TE/DUTS-TE-Image"
YTBVOS_PATH: "/home/admin/workspace/project/data/datasets/YTBVOS"
HFLICKER_PATH: "/home/admin/workspace/project/data/datasets/HFlickr"




# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./weights/pretrained/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W18_SMALL: "/home/admin/workspace/project/data/weights/hrnet_w18_small_model_v2.pth"
  HRNETV2_W32: "./weights/pretrained/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./weights/pretrained/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./weights/pretrained/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W64: "./weights/pretrained/hrnetv2_w64_imagenet_pretrained.pth"
  MIT_B5: "./weights/pretrained/mit_b5_converted.pth"
  MIT_B4: "./weights/pretrained/mit_b4_converted.pth"
  MIT_B3: "./weights/pretrained/mit_b3_converted.pth"
  MIT_B2: "./weights/pretrained/mit_b2_converted.pth"
  MIT_B1: "./weights/pretrained/mit_b1_converted.pth"
  MIT_B0: "./weights/pretrained/mit_b0_converted.pth"
  HRF_BASE: "./weights/pretrained/hrt_base.pth"
  SWIN_BASE: "./weights/pretrained/swin_base_patch4_window12_384_22k.pth"
  SWIN_LARGE: "./weights/pretrained/swin_large_patch4_window12_384_22k.pth"
  MAE_BASE: "./weights/pretrained/mae_pretrain_vit_base.pth"
  MAE_LARGE: "./weights/pretrained/mae_pretrain_vit_large.pth"
  MAE_HUGE: "./weights/pretrained/mae_pretrain_vit_huge.pth"
  SEGFORMER_B0: "/home/admin/workspace/project/data/weights/Segformer/mit_b0.pth"
  SEGFORMER_B1: "/home/admin/workspace/project/data/weights/Segformer/mit_b1.pth"
  SEGFORMER_B3: "/home/admin/workspace/project/data/weights/Segformer/mit_b3.pth"
  PPLCNET_X1 : "/home/admin/workspace/project/data/weights/PPLC/PP-LCNet/PPLCNet_x1_0_ssld_pretrained.pth"
  MOBILENETV2: "/home/admin/workspace/project/data/weights/mobilenetV2-15498621.pth"











